# Generated by Django 3.1.1 on 2021-07-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminABC', '0002_remove_account_notificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='about',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='account',
            name='middlename',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='account',
            name='votercard',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=19),
        ),
    ]
