# Generated by Django 3.1.1 on 2021-07-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminABC', '0003_auto_20210723_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='code',
            field=models.CharField(default='', max_length=3),
        ),
    ]
