# Generated by Django 3.1.1 on 2021-07-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminABC', '0004_lga_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.ward'),
        ),
    ]
