# Generated by Django 3.1.1 on 2021-07-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminABC', '0006_remove_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='internalId',
            field=models.IntegerField(default=None),
        ),
    ]
