# Generated by Django 3.1.1 on 2021-07-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminABC', '0010_auto_20210728_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='lga',
            name='senatorialzone',
        ),
        migrations.RemoveField(
            model_name='pollingunit',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='superuseradmin',
            name='superUser',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='lga',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='Lga',
        ),
        migrations.DeleteModel(
            name='PollingUnit',
        ),
        migrations.DeleteModel(
            name='SenatorialZone',
        ),
        migrations.DeleteModel(
            name='SuperUserAdmin',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
