# Generated by Django 3.1.1 on 2021-07-29 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminABC', '0012_auto_20210728_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalId', models.CharField(default=None, max_length=50)),
                ('image', models.FileField(default=None, upload_to='')),
                ('password', models.CharField(max_length=350)),
                ('firstname', models.CharField(default='', max_length=350)),
                ('middlename', models.CharField(default='', max_length=350)),
                ('lastname', models.CharField(default='', max_length=350)),
                ('phone', models.CharField(default='', max_length=19)),
                ('gender', models.CharField(default='', max_length=19)),
                ('votercard', models.CharField(default='', max_length=150)),
                ('age', models.CharField(default='', max_length=150)),
                ('registrationNumber', models.CharField(max_length=50)),
                ('isOldMember', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isSuperUser', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('office', models.CharField(default=None, max_length=350)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.lga')),
                ('pollingUnit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.pollingunit')),
                ('ward', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.ward')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('title', models.TextField()),
                ('image', models.FileField(default=None, upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.demoaccount')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PostUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.post')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.demoaccount')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.post')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.demoaccount')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminABC.post')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
