# Generated by Django 3.1.1 on 2021-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuntuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
    ]
