# Generated by Django 3.1.1 on 2021-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuntuapp', '0002_comment_like_post_postupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(default='', max_length=19),
        ),
    ]
