# Generated by Django 3.1.1 on 2021-02-28 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obuntuapp', '0003_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUserAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('superUser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obuntuapp.account')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
