# Generated by Django 3.1.1 on 2021-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuntuapp', '0003_auto_20210409_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
