# Generated by Django 3.1.1 on 2021-04-10 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obuntuapp', '0005_like_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('following', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obuntuapp.account')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
