# Generated by Django 3.1.1 on 2021-04-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuntuapp', '0008_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
