# Generated by Django 3.1.1 on 2021-04-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obuntuapp', '0010_account_notificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.CharField(default='', max_length=150),
        ),
    ]
