# Generated by Django 3.1.1 on 2021-04-19 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obuntuapp', '0011_account_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('video', models.FileField(default=None, upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obuntuapp.account')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obuntuapp.videocategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
