# Generated by Django 3.1.1 on 2021-04-19 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obuntuapp', '0012_video_videocategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obuntuapp.account')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
